version: '3.3'

services:
  db:
    image: mysql:5
    container_name: mysql_prueba
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: hospital_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_prueba
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
